title:            Balzac
tagline:          A beautiful theme.
description:      Describe your website.
canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           lizhao
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          cole@coletownsend.com
  twitter:        twnsndco
  github:         289048093
  dribbble:       coletownsend
  disqus:         itmeats
  location:       "shenzhen, CN"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/289048093
    external: true
  - title: Cole Who?
    url: http://itmeats.github.io
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
